# Generated by Django 4.1.7 on 2023-03-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_alter_room_roomnumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_games_played", models.IntegerField(default=0)),
                ("num_wins", models.IntegerField(default=0)),
                ("num_draws", models.IntegerField(default=0)),
                ("num_losses", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "game_data",},
        ),
    ]
